(package "eglot-uniteai"
         "0.1.0"
         "Eglot Clients for UniteAI")

(website-url "https://github.com/emacs-openai/eglot-uniteai")
(keywords "convenience" "ai")

(package-file "eglot-uniteai.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "eglot")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
